declare const styles: {
  documentLibrary: string;
  mainHeader: string;
  mainTitle: string;
  foldersContainer: string;
  folderSection: string;
  folderHeader: string;
  folderTitle: string;
  viewAllButton: string;
  documentsGrid: string;
  documentCard: string;
  cardContent: string;
  documentTitle: string;
  documentMeta: string;
  documentDescription: string;
  cardActions: string;
  cardActionButton: string;
  actionIcon: string;
  header: string;
  headerContent: string;
  backIcon: string;
  breadcrumbIcon: string;
  breadcrumb: string;
  description: string;
  loading: string;
  documentsSection: string;
  sectionTitle: string;
  documentsTable: string;
  tableHeader: string;
  headerCell: string;
  sortIcon: string;
  tableBody: string;
  tableRow: string;
  selected: string;
  nameCell: string;
  checkbox: string;
  checkIcon: string;
  fileIcon: string;
  fileName: string;
  dataCell: string;
  actionsCell: string;
  moreButton: string;
  noDocuments: string;
  noDocumentsIcon: string;
};

export = styles;